# The Minesweeper Problem
Given an NxN grid of values, where -1 indicates a bomb and 0-8 indicate the number of surrounding bombs, and m bombs, find all grids that don't have a bomb without clicking on any bombs. Assume your first click will not be a bomb.

### Create an NxN grid with M bombs

In [1]:
import numpy as np

def create_grid(n, m, row_i, col_i):
    bombs_remaining = m

    grid = np.zeros((n,n))

    def bump_adjacent(row, col):
        max_row = n-1
        max_col = n-1

        for i in range(row - 1, row + 2):
            for j in range(col - 1, col + 2):
                if 0 <= i <= max_row and 0 <= j <= max_col and (i != row or j != col):
                    if grid[i][j] > -1:
                        grid[i][j] += 1

    while bombs_remaining:
        row = np.random.randint(0, n)
        col = np.random.randint(0, n)
    
        if (row == row_i and col == col_i) or grid[row][col] == -1:
            pass
        else:
            grid[row][col] = -1
            bump_adjacent(row, col)
            bombs_remaining -= 1

    return grid

### Functions to play the game

In [2]:
def play_game(n, m):
    name = input("Hello! Welcome to Minesweeper. What is your name?")
    print("hello " + name)

    curr = np.full((n, n), "N")
    print(curr)

    global safe
    
    safe = n*n - m

    def click_adjacent(row,col):
        max_row = n-1
        max_col = n-1

        for i in range(row - 1, row + 2):
            for j in range(col - 1, col + 2):
                if 0 <= i <= max_row and 0 <= j <= max_col and (i != row or j != col):
                    on_click(i,j)

    def on_click(i, j):
        global safe
        # if it's already been clicked, do nothing
        if curr[i][j] != "N":
            return False
        
        curr[i][j] = int(grid[i][j])
        safe -= 1

        match grid[i][j]:
            case 0.0:
                click_adjacent(i,j)
            case -1.0: 
                return True
            case _: 
                pass
        return False

    row_i = int(input("Next Click ROW: "))
    col_i = int(input("Next Click COLUMN: "))

    grid = create_grid(n,m, row_i, col_i)
    game_over = on_click(row_i, col_i)

    while (not game_over and safe):
        print(curr)
        row = int(input("Next Click ROW: "))
        col = int(input("Next Click COLUMN: "))
        game_over = on_click(row, col)

    print(grid)

    if game_over:
        print("GAME OVER")
    else:
        print("YOU WIN")

### Play

In [4]:
play_game(4, 6)

hello Brandon
[['N' 'N' 'N' 'N']
 ['N' 'N' 'N' 'N']
 ['N' 'N' 'N' 'N']
 ['N' 'N' 'N' 'N']]
[['N' 'N' 'N' 'N']
 ['N' '2' 'N' 'N']
 ['N' 'N' 'N' 'N']
 ['N' 'N' 'N' 'N']]
[['N' 'N' 'N' 'N']
 ['N' '2' 'N' 'N']
 ['N' 'N' 'N' 'N']
 ['N' 'N' 'N' '1']]
[['N' 'N' 'N' 'N']
 ['N' '2' 'N' 'N']
 ['N' 'N' '4' 'N']
 ['N' 'N' 'N' '1']]
[[-1.  1.  2. -1.]
 [ 2.  2.  4. -1.]
 [ 2. -1.  4. -1.]
 [ 2. -1.  3.  1.]]
GAME OVER
